config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  mount Blacklight::Engine => '/'
  mount BlacklightDynamicSitemap::Engine => '/'
  mount Arclight::Engine => '/'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/queues'

  # DUL CUSTOMIZATION: note that component URLs have underscores; collections don't
  def collection_slug_constraint
    /[a-z0-9\-]+/
  end

  # DUL CUSTOMIZATION: homepage
  root to: 'pages#home'

  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
    concerns :range_searchable

    # concerns :range_searchable
  end
  devise_for :users

  concern :exportable, Blacklight::Routes::Exportable.new
  concern :hierarchy, Arclight::Routes::Hierarchy.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :hierarchy
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end
  # rubocop:enable Metrics/BlockLength

  resources :ua_record_groups, only: [:index], as: 'ua_record_groups', path: '/collections/ua-record-groups',
                               controller: 'ua_record_groups'

  # DUL CUSTOMIZATION: Download the source EAD XML file using the collection slug
  get '/catalog/:id/xml', action: 'ead_download', controller: 'catalog', as: 'ead_download',
                          constraints: { id: collection_slug_constraint }

  # DUL CUSTOMIZATION: Render a sitemap on-the-fly from a query (if configured)
  get '/custom_sitemaps/:id', controller: 'custom_sitemaps', action: 'index', defaults: { format: 'xml' },
                              constraints: ->(request) { CUSTOM_SITEMAP_CONFIG.key?(request.params[:id]) }

  post '/index_finding_aids', to: 'index_finding_aids#create'

  # Default health check introduced in Rails 7.1
  get 'up', to: 'rails/health#show', as: :rails_health_check
end

app/views/shared/_contact.html.erb
<div id="announcement" role="complementary">
  <div class="contact-wrapper position-fixed">
    <%= link_to t('dul_arclight.contact.title'),
      ask_rubenstein_url,
      class: "btn btn-sm btn-primary",
      target: "_blank" %>
  </div>
</div>

app/views/shared/_footer.html.erb
<%# TODO: determine whether to add DUL footer links... %>
<%= render 'shared/contact' %>
<%= render 'shared/modal_advanced_search' %>

app/views/shared/_harmful_language.html.erb
<p class="harmful-language-statement">
  <span class="fa fa-info-circle mr-1 text-muted"></span> Some materials and descriptions may include offensive content. <a href="https://library.duke.edu/about/statement-potentially-harmful-language-library-descriptions" aria-label="Statement on Potentially Harmful Language in Library Descriptions" class="ml-1 fw-semibold" data-matomo-event-name="harmful language statement link">More info</a>
</p>

app/views/shared/_matomo_analytics_body.html.erb
<%# Matomo Analytics code that lives in the <body>.              -%>
<%# Note we cannot put the Matomo-supplied tracking code in      -%>
<%# the <head> because of Hotwire/Turbo, which doesn't reload    -%>
<%# the contents of the <head> when transitioning between pages. -%>

<div id="matomo-analytics-configs"
  data-matomo-analytics-host="<%= DulArclight.matomo_analytics_host %>"
  data-matomo-analytics-site-id="<%= DulArclight.matomo_analytics_site_id %>"
  data-matomo-analytics-debug="<%= DulArclight.matomo_analytics_debug %>">
</div>

<%# https://developer.matomo.org/guides/tracking-javascript-guide %>
<!-- Matomo -->
<script>
  var _paq = window._paq = window._paq || [];

  <%# Custom Dimensions -%>
  <%# https://developer.matomo.org/guides/tracking-javascript-guide#custom-dimensions -%>
  _paq.push(['setCustomDimension', customDimensionId = 1, customDimensionValue = '<%= matomo_collection_id %>']);
  _paq.push(['setCustomDimension', customDimensionId = 2, customDimensionValue = '<%= matomo_page_type %>']);

  <%# Turbo makes this necessary... we need to explicitly   -%>
  <%# set the page title and URL sent to Google for each    -%>
  <%# pageview, else it would not update between pages as a -%>
  <%# user navigates. %>
  _paq.push(['setDocumentTitle', document.title]);
  _paq.push(['setCustomUrl', window.location.href]);

  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);

  (function() {
    var u="//<%= DulArclight.matomo_analytics_host %>/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '<%= DulArclight.matomo_analytics_site_id %>']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();

  <% if DulArclight.matomo_analytics_debug == 'true' %>
  console.log(
    [
      'Matomo Collection ID: <%= matomo_collection_id %>',
      'Matomo Page Type: <%= matomo_page_type %>',
      'Matomo Site ID: <%= DulArclight.matomo_analytics_site_id %>',
      'Matomo Host: <%= DulArclight.matomo_analytics_host %>'
    ].join(' --- '));
  <% end %>

</script>
<!-- End Matomo Code -->

app/views/shared/_mobile_menu.html.erb
<%# Combine top-level nav links from repository menu bar & the DUL shared mast %>
<%# into one, so we have only one hamburger menu. %>
<div id="mobile-only-menu" class="collapse navbar-collapse">
  <nav id="mobile-only-menu-nav" class="navbar navbar-expand-lg navbar-dark">
    <div class="container">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item flex-fill flex-grow-1">
          <a class="nav-link" href="https://library.duke.edu/my-accounts">My Accounts</a>
        </li>
        <li class="nav-item flex-fill">
          <a class="nav-link" href="<%= ask_rubenstein_url %>">Ask a Librarian</a>
        </li>
        <%# links from DUL nav %>
        <li class="nav-item flex-fill">
          <a class="nav-link" href="https://library.duke.edu/find">Search &amp; Find</a>
        </li>
        <li class="nav-item flex-fill">
          <a class="nav-link" href="https://library.duke.edu/using">Using the Library</a>
        </li>
        <li class="nav-item flex-fill">
          <a class="nav-link" href="https://library.duke.edu/research">Research Support</a>
        </li>
        <li class="nav-item flex-fill">
          <a class="nav-link" href="https://library.duke.edu/course-support">Course Support</a>
        </li>
        <li class="nav-item flex-fill">
          <a class="nav-link" href="https://library.duke.edu/libraries">Libraries</a>
        </li>
        <li class="nav-item flex-fill">
          <a class="nav-link" href="https://library.duke.edu/about">About</a>
        </li>
      </ul>
    </div>
  </nav>
</div>

app/views/shared/_modal_advanced_search.html.erb
<%# We are not using Blacklight::System::ModalComponent or the #blacklight-modal %>
<%# here because we need to get the current collection scope into the form to    %>
<%# toggle search within collection, which is difficult to do when the contents  %>
<%# are loaded via AJAX. %>
<div class="modal fade" id="advanced-modal" tabindex="-1" aria-label="Advanced Search" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title h4">Advanced Search</h2>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%# Suppress autocomplete so it doesn't get mixed up with the non-modal searchbox. %>
        <%= render SearchBarComponent.new(
            url: search_action_url,
            params: search_state.params_for_search.except(:qt),
            autocomplete_path: ''
          ) %>
      </div>
      <div class="modal-footer">
        <%= link_to 'More Advanced Search Options', advanced_search_catalog_url, data: { turbo: false } %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_search_extra_controls.html.erb
<%# Advanced search link and bookmarks button %>

<div class="search-extra-controls mt-2">

    <%= link_to t('dul_arclight.advanced_search.title'), '#',
          class: 'advanced-search-link',
          data: { bs_toggle: 'modal', bs_target: '#advanced-modal' } %>

    <%= link_to bookmarks_path, id:'bookmarks_nav' do %>
      <i class="fas fa-bookmark"></i> <span class="bookmarks-label"><%= t('blacklight.header_links.bookmarks') %></span>
      <span class="open-paren">(</span><span data-role='bookmark-counter' data-bookmark-count="<%= current_or_guest_user.bookmarks.count %>"><%= current_or_guest_user.bookmarks.count %></span><span class="close-paren">)</span>
    <% end %>

</div>

app/views/shared/_site_alert.html.erb
<div class="alert alert-warning site-alert" role="alert">
  <% if I18n.exists?('dul_arclight.site_alert.title') %>
    <h2 class="h3"><%= t('dul_arclight.site_alert.title') %></h2>
  <% end %>
  <div><%= t('dul_arclight.site_alert.message_html').html_safe %></div>
</div>

app/views/shared/_user_util_links.html.erb
<%# Overrides Blacklight core partial %>
<%# https://github.com/projectblacklight/blacklight/blob/main/app/views/shared/_user_util_links.html.erb %>

<ul class="navbar-nav">
    <%#  my account %>
    <li class="nav-item">
      <a href="https://library.duke.edu/my-accounts" class="nav-link" title ="<%= t('blacklight.header_links.my_account') %>">
        <span class="nav-icon"><i class="fas fa-user"></i></span><span class="nav-label"><%= t('blacklight.header_links.my_account') %></span>
      </a>
    </li>


    <%#  ask a question %>
    <li class="nav-item">
      <a href="<%= ask_rubenstein_url %>" class="nav-link" title="Ask a Librarian">
        <span class="nav-icon"><i class="fas fa-comment"></i></span><span class="nav-label">Ask</span>
      </a>
    </li>


    <%#  trigger dul mast %>
    <li class="nav-item full-menu-toggle-wrapper">
      <a href="#" id="full-menu-toggle" class="nav-link full-menu" title="<%= t('blacklight.header_links.menu_long')%>" data-bs-toggle="collapse" data-bs-target="#mobile-only-menu" aria-controls="mobile-only-menu" aria-expanded="false"">
        <span class="nav-icon"><i class="fas fa-bars"></i></span><span class="nav-label">Menu<%#= t('blacklight.header_links.menu') %></span>
      </a>
    </li>
</ul>